const $=id=>document.getElementById(id);
const messages=['Tu sonrisa tiene esa bonita costumbre de alegrarme el día.','Hay algo en tu forma de ser que vuelve especial hasta lo más sencillo.','Me gusta pensarte. Y me gusta todavía más coincidir contigo.','Si hoy te faltaba una razón para sonreír, ojalá este detalle sea una.','Entre todas las cosas bonitas que podía regalarte, elegí un poquito de sol para ti.'];
let found=new Set(),stage='welcome',opening=false;
function showScene(next){stage=next;for(const id of ['welcome','lightsScene','gift'])$(id).hidden=id!==next;}
async function openEnvelope(){if(stage!=='welcome'||opening)return;opening=true;$('envelope').classList.add('opening');await new Promise(r=>setTimeout(r,550));showScene('lightsScene');opening=false;$('lights').firstElementChild.focus({preventScroll:true});}
function discover(index){if(!Number.isInteger(index)||index<0||index>4)throw Error('Elige una lucecita del 1 al 5.');if(stage!=='lightsScene'||$('note').open)throw Error('Primero abre el sobre o termina de leer el mensaje.');if(found.has(index))return{messages:found.size};found.add(index);const button=$('lights').children[index];button.disabled=true;button.setAttribute('aria-label',`Mensaje ${index+1} descubierto`);$('noteNumber').textContent=`UN MENSAJITO PARA TI · ${found.size} DE 5`;$('noteText').textContent=messages[index];$('count').textContent=`${found.size} de 5 mensajes descubiertos`;$('hiddenBouquet').style.opacity=String(.045+found.size*.055);$('hiddenBouquet').style.filter=`blur(${18-found.size*2}px)`;$('continue').textContent=found.size===5?'Hay algo más para ti ✨':'Guardar este mensajito 💛';$('note').showModal();return{messages:found.size,message:messages[index]};}
function afterNote(){if(stage!=='lightsScene')return;if(found.size===5){$('reveal').hidden=false;$('reveal').focus({preventScroll:true});}else{Array.from($('lights').children).find(b=>!b.disabled)?.focus({preventScroll:true});}}
function petals(){if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;$('petals').replaceChildren();for(let i=0;i<18;i++){const p=document.createElement('span');p.className='petal';p.textContent=i%3?'🌼':'💛';p.style.left=(i*37%100)+'vw';p.style.animationDelay=(i*.17)+'s';$('petals').append(p);setTimeout(()=>p.remove(),10500);}}
function reveal(){if(found.size!==5||$('note').open||stage!=='lightsScene')throw Error('Descubre los cinco mensajes antes de abrir la sorpresa.');showScene('gift');petals();$('letterButton').focus({preventScroll:true});return{stage:'gift'};}
function reset(){found.clear();opening=false;$('envelope').classList.remove('opening');$('lights').replaceChildren();for(let i=0;i<5;i++){const b=document.createElement('button');b.className='light';b.textContent='✦';b.setAttribute('aria-label',`Descubrir mensaje de la lucecita ${i+1}`);b.onclick=()=>discover(i);$('lights').append(b);}$('count').textContent='0 de 5 mensajes descubiertos';$('hiddenBouquet').style.opacity='.045';$('hiddenBouquet').style.filter='blur(18px)';$('reveal').hidden=true;$('petals').replaceChildren();showScene('welcome');}
$('envelope').onclick=openEnvelope;$('continue').onclick=()=>$('note').close();$('note').addEventListener('close',afterNote);$('reveal').onclick=reveal;$('letterButton').onclick=()=>{$('letter').showModal();petals();};$('close').onclick=()=>$('letter').close();$('again').onclick=()=>{$('letter').close();reset();$('envelope').focus({preventScroll:true});};reset();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'open_vanesita_envelope',description:'Abre el sobre e inicia la sorpresa para Vanesita.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>{await openEnvelope();return{stage};}},{name:'discover_vanesita_light',description:'Abre un mensaje de una lucecita; hay que cerrar el mensaje antes de abrir otro.',inputSchema:{type:'object',properties:{light:{type:'integer',minimum:1,maximum:5}},required:['light'],additionalProperties:false},execute:input=>discover(input.light-1)},{name:'close_vanesita_message',description:'Cierra el mensaje actual para continuar descubriendo la sorpresa.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{$('note').close();afterNote();return{messages:found.size};}},{name:'reveal_vanesita_bouquet',description:'Muestra el ramo regalado cuando los cinco mensajes se han descubierto.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:reveal}]){try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
